#!/bin/bash

INPUT_DIR="pokemon_data"
OUTPUT_CSV="pokemon_report.csv"

echo "Name,Height (m),Weight (kg)" > "$OUTPUT_CSV"

awk_script='
BEGIN { h_sum=0; w_sum=0; count=0 }
{
    name = $1;
    height = $2 / 10;
    weight = $3 / 10;
    h_sum += height;
    w_sum += weight;
    count++;
    printf "%s,%.1f,%.1f\n", name, height, weight
}
END {
    printf "\nAverage Height: %.2f m\n", h_sum / count
    printf "Average Weight: %.2f kg\n", w_sum / count
}'

for file in "$INPUT_DIR"/*.json; do
    name=$(jq -r '.name' "$file" | sed 's/.*/\u&/')
    height=$(jq -r '.height' "$file")
    weight=$(jq -r '.weight' "$file")
    echo "$name $height $weight"
done | awk "$awk_script" >> "$OUTPUT_CSV"

echo "CSV Report generated at: $OUTPUT_CSV"
